import { useEffect, useState, type FormEvent } from 'react'
import { Check, Dumbbell, Plus, Sparkles, UsersRound } from 'lucide-react'
import toast from 'react-hot-toast'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { api, getErrorMessage, money } from '../lib/api'
import type { ApiResponse, MembershipPlan, PtPackage } from '../types'

export function PackagesPage(){const{user}=useAuth();const navigate=useNavigate();const owner=user?.roles.includes('OWNER');const member=user?.roles.includes('MEMBER');const[plans,setPlans]=useState<MembershipPlan[]>([]);const[pts,setPts]=useState<PtPackage[]>([]);const[show,setShow]=useState(false)
 const load=()=>Promise.all([api.get<ApiResponse<MembershipPlan[]>>(`/catalog/memberships${owner?'?all=true':''}`),api.get<ApiResponse<PtPackage[]>>(`/catalog/pt-packages${owner?'?all=true':''}`)]).then(([a,b])=>{setPlans(a.data.data);setPts(b.data.data)}).catch(e=>toast.error(getErrorMessage(e)));/* oxlint-disable-next-line react-hooks/exhaustive-deps -- reload is also reused after mutations */ useEffect(()=>{void load()},[])
 const buy=async(productType:string,productId:string)=>{try{const{data}=await api.post<ApiResponse<unknown>>('/orders',{productType,productId});toast.success(data.message||'Đã tạo đơn.');navigate('/orders')}catch(e){toast.error(getErrorMessage(e))}}
 return <><PageHead eyebrow="DANH MỤC DỊCH VỤ" title="Đầu tư cho phiên bản tốt hơn" text="Gói Gym tính theo tháng; gói PT tính theo số buổi hoàn thành.">{owner&&<button className="btn btn-primary" onClick={()=>setShow(!show)}><Plus/> Tạo gói mới</button>}</PageHead>{show&&<CreatePlan onDone={()=>{setShow(false);void load()}}/>}<div className="section-heading"><div><span className="eyebrow dark">GÓI HỘI VIÊN</span><h3>Quyền truy cập phòng tập</h3></div><span>{plans.length} lựa chọn</span></div><div className="pricing-grid">{plans.map((plan,i)=><article className={`price-card ${i===1?'featured':''} ${!plan.isActive?'disabled-card':''}`} key={plan.id}>{i===1&&<span className="popular"><Sparkles/> PHỔ BIẾN</span>}<div className="price-icon"><Dumbbell/></div><h3>{plan.name}</h3><p>{plan.description}</p><strong className="price">{money(plan.price)}</strong><div className="benefits"><span><Check/> {plan.type==='DURATION'?`${Math.round((plan.durationDays||0)/30)} tháng không giới hạn`:`${plan.visitLimit} lượt tập`}</span><span><Check/> Gia hạn nối tiếp, không chồng ngày</span><span><Check/> Theo dõi lịch sử check-in</span></div>{member&&<button className="btn btn-dark btn-wide" onClick={()=>buy('MEMBERSHIP',plan.id)} disabled={!plan.isActive}>Chọn gói này</button>}{owner&&<span className={`status ${plan.isActive?'paid':'cancelled'}`}>{plan.isActive?'Đang kinh doanh':'Đã ngừng'}</span>}</article>)}</div><div className="section-heading spaced"><div><span className="eyebrow dark">HUẤN LUYỆN CÁ NHÂN</span><h3>Gói tập cùng PT</h3></div></div><div className="pricing-grid compact">{pts.map(pkg=><article className="price-card pt-card" key={pkg.id}><div className="price-icon"><UsersRound/></div><h3>{pkg.name}</h3><p>{pkg.description}</p><strong className="price">{money(pkg.price)}</strong><div className="session-count"><b>{pkg.sessionCount}</b><span>buổi 1:1</span></div>{member&&<button className="btn btn-dark btn-wide" onClick={()=>buy('PT_PACKAGE',pkg.id)}>Chọn gói PT</button>}</article>)}</div></>}

function PageHead({eyebrow,title,text,children}:{eyebrow:string;title:string;text:string;children?:React.ReactNode}){return <section className="hero-row"><div><span className="eyebrow dark">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div><div className="hero-actions">{children}</div></section>}
function CreatePlan({onDone}:{onDone:()=>void}){const[type,setType]=useState<'MEMBERSHIP'|'PT_PACKAGE'>('MEMBERSHIP');const[form,setForm]=useState({name:'',description:'',price:'',duration:'1'});const submit=async(e:FormEvent)=>{e.preventDefault();try{const url=type==='MEMBERSHIP'?'/catalog/memberships':'/catalog/pt-packages';const payload=type==='MEMBERSHIP'?{name:form.name,description:form.description,price:Number(form.price),type:'DURATION',durationDays:Number(form.duration)*30}:{name:form.name,description:form.description,price:Number(form.price),sessionCount:Number(form.duration)};const{data}=await api.post<ApiResponse<unknown>>(url,payload);toast.success(data.message);onDone()}catch(e){toast.error(getErrorMessage(e))}};return <form className="card inline-form" onSubmit={submit}><label>Loại<select value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="MEMBERSHIP">Gói Gym theo tháng</option><option value="PT_PACKAGE">Gói PT theo buổi</option></select></label><label>Tên gói<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Giá (VND)<input type="number" min="1" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/></label>{type==='MEMBERSHIP'?<label>Thời hạn<select value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}><option value="1">1 tháng</option><option value="2">2 tháng</option><option value="3">3 tháng</option></select></label>:<label>Số buổi<input type="number" min="1" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})} required/></label>}<button className="btn btn-primary"><Plus/> Lưu gói</button></form>}
