import { useEffect, useState, type FormEvent } from 'react'
import { Plus, Search, ShieldCheck, Trash2 } from 'lucide-react'
import toast from 'react-hot-toast'
import { useAuth } from '../context/AuthContext'
import { api, getErrorMessage } from '../lib/api'
import type { ApiResponse } from '../types'

interface MemberRow {id:string;email:string;fullName:string;phone?:string;status:string;createdAt:string;memberProfile?:{memberCode:string;memberships:unknown[];ptPackages:unknown[]}}
interface StaffRow {id:string;email:string;fullName:string;status:string;roles:Array<{role:{code:string;name:string}}>}

export function MembersPage(){const{user}=useAuth();const[rows,setRows]=useState<MemberRow[]>([]);const[q,setQ]=useState('');const owner=user?.roles.includes('OWNER');const load=()=>api.get<ApiResponse<MemberRow[]>>('/users/members').then(r=>setRows(r.data.data)).catch(e=>toast.error(getErrorMessage(e)));useEffect(()=>{void load()},[]);const remove=async(member:MemberRow)=>{if(!window.confirm(`Xóa tài khoản ${member.fullName} (${member.email})? Hành động này không thể hoàn tác.`))return;try{const{data}=await api.delete<ApiResponse<unknown>>(`/users/members/${member.id}`);toast.success(data.message);await load()}catch(error){toast.error(getErrorMessage(error))}};const visible=rows.filter(x=>`${x.fullName} ${x.email} ${x.memberProfile?.memberCode}`.toLowerCase().includes(q.toLowerCase()));return <><Header eyebrow="DANH SÁCH HỘI VIÊN" title="Hội viên" text="Hồ sơ, trạng thái và quyền lợi được quản lý tập trung."/><div className="card table-card"><div className="table-tools"><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm tên, email hoặc mã hội viên..."/></div><span>{visible.length} hội viên</span></div><div className="table-wrap"><table><thead><tr><th>Hội viên</th><th>Mã</th><th>Liên hệ</th><th>Quyền lợi</th><th>Trạng thái</th>{owner&&<th>Thao tác</th>}</tr></thead><tbody>{visible.map(x=><tr key={x.id}><td><div className="person"><span>{x.fullName[0]}</span><div><strong>{x.fullName}</strong><small>Tham gia {new Date(x.createdAt).toLocaleDateString('vi-VN')}</small></div></div></td><td><code>{x.memberProfile?.memberCode}</code></td><td>{x.email}<small>{x.phone||'Chưa có số điện thoại'}</small></td><td>{x.memberProfile?.memberships?.length||0} Gym · {x.memberProfile?.ptPackages?.length||0} PT</td><td><span className={`status ${x.status==='ACTIVE'?'paid':'cancelled'}`}>{x.status==='ACTIVE'?'Hoạt động':x.status==='UNVERIFIED'?'Chưa xác thực':'Tạm khóa'}</span></td>{owner&&<td><button className="icon-action bad" title="Xóa tài khoản" aria-label={`Xóa tài khoản ${x.fullName}`} onClick={()=>void remove(x)}><Trash2/></button></td>}</tr>)}</tbody></table></div></div></>}

export function StaffPage(){const[rows,setRows]=useState<StaffRow[]>([]);const[show,setShow]=useState(false);const load=()=>api.get<ApiResponse<StaffRow[]>>('/users/staff').then(r=>setRows(r.data.data)).catch(e=>toast.error(getErrorMessage(e)));useEffect(()=>{void load()},[]);return <><Header eyebrow="ĐỘI NGŨ VẬN HÀNH" title="Nhân sự" text="Tài khoản nhân sự chỉ được tạo bởi Chủ phòng."><button className="btn btn-primary" onClick={()=>setShow(!show)}><Plus/> Thêm nhân sự</button></Header>{show&&<StaffForm onDone={()=>{setShow(false);void load()}}/>}<div className="people-grid">{rows.map(x=><article className="person-card" key={x.id}><div className="person-avatar">{x.fullName[0]}</div><span className={`status ${x.status==='ACTIVE'?'paid':'cancelled'}`}>{x.status==='ACTIVE'?'Hoạt động':'Tạm khóa'}</span><h3>{x.fullName}</h3><p>{x.email}</p><div className="role-line"><ShieldCheck/>{x.roles.map(r=>r.role.name).join(', ')}</div></article>)}</div></>}

function StaffForm({onDone}:{onDone:()=>void}){const[form,setForm]=useState({fullName:'',email:'',password:'',role:'RECEPTIONIST',specialties:''});const submit=async(e:FormEvent)=>{e.preventDefault();try{const{data}=await api.post<ApiResponse<unknown>>('/users/staff',form);toast.success(data.message);onDone()}catch(e){toast.error(getErrorMessage(e))}};return <form className="card inline-form" onSubmit={submit}><label>Họ tên<input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Mật khẩu khởi tạo<input type="password" minLength={8} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Vai trò<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="RECEPTIONIST">Lễ tân</option><option value="TRAINER">Huấn luyện viên (PT)</option></select></label><button className="btn btn-primary"><Plus/> Tạo tài khoản</button></form>}
function Header({eyebrow,title,text,children}:{eyebrow:string;title:string;text:string;children?:React.ReactNode}){return <section className="hero-row"><div><span className="eyebrow dark">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div><div>{children}</div></section>}
